version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm test --prefix client -- --coverage
      - store_artifacts:
          path: client/coverage